from enum import Enum


class Position(Enum):
    GOALKEEPER = "GK"
    RIGHT_BACK = "RB"
    CENTER_BACK = "CB"
    LEFT_BACK = "LB"
    RIGHT_WING_BACK = "RWB"
    LEFT_WING_BACK = "LWB"
    DEFENSIVE_MIDFIELDER = "CDM"
    RIGHT_MIDFIELDER = "RM"
    CENTRAL_MIDFIELDER = "CM"
    LEFT_MIDFIELDER = "LM"
    RIGHT_WINGER = "RW"
    ATTACKING_MIDFIELDER = "CAM"
    LEFT_WINGER = "LW"
    LEFT_INSIDE_FORWARD = "LIF"
    RIGHT_INSIDE_FORWARD = "RIF"
    CENTRE_FORWARD = "CF"
